# Generated by Django 3.0.7 on 2020-06-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepitch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hasAppeal',
            field=models.BooleanField(default=False),
        ),
    ]
